repositories:
  - name: elastic
    url: https://helm.elastic.co

helmDefaults:
  wait: true
  createNamespace: true
  historyMax: 3
  cleanupOnFail: true

releases:
  - name: elasticsearch
    namespace: logging
    chart: elastic/elasticsearch
    values:
      - replicas: 1
      - minimumMasterNodes: 1
      - antiAffinity: "soft"
      - secret:
          password: password

  - name: filebeat
    namespace: logging
    chart: elastic/filebeat
    needs:
      - logstash
    values:
      - daemonset:
          hostNetworking: true
          filebeatConfig:
            filebeat.yml: |
              filebeat.inputs:
                - type: container
                  paths:
                    - /var/log/containers/*.log
                  processors:
                    - add_kubernetes_metadata:
                        host: ${NODE_NAME}
                        matchers:
                          - logs_path:
                              logs_path: "/var/log/containers/"
              output.logstash:
                hosts: '${LOGSTASH_URL}'
          extraEnvs:
            - name: LOGSTASH_URL
              value: logstash-logstash.logging:5044

  - name: logstash
    namespace: logging
    chart: elastic/logstash
    needs:
      - elasticsearch
    values:
      - logstashConfig:
          logstash.yml: |
            http.host: "0.0.0.0"
      - logstashPipeline:
          logstash.conf: |
            input {
              beats {
                port => 5044
              }
            }
            filter {
            }
            output {
                elasticsearch {
                  index => "logstash-%{[@metadata][beat]}"
                  hosts => [ "${ELASTICSEARCH_HOSTS}" ]
                  user => "${ELASTICSEARCH_USER}"
                  password => "${ELASTICSEARCH_PASSWORD}"
                  cacert => '/etc/logstash/certificates/ca.crt'
                }
            }
      - antiAffinity: "soft"
      - extraPorts:
          - name: beats
            containerPort: 5044
      - service:
          annotations: {}
          type: ClusterIP
          loadBalancerIP: ""
          ports:
            - name: beats
              port: 5044
              protocol: TCP
              targetPort: 5044
      - extraEnvs:
          - name: ELASTICSEARCH_HOSTS
            value: https://elasticsearch-master:9200
          - name: ELASTICSEARCH_USER
            valueFrom:
              secretKeyRef:
                name: elasticsearch-master-credentials
                key: username
                optional: false
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elasticsearch-master-credentials
                key: password
                optional: false
      - secretMounts:
          - name: logstash-certificates
            secretName: elasticsearch-master-certs
            path: /etc/logstash/certificates/ca.crt
            subPath: ca.crt

  - name: kibana
    namespace: logging
    chart: elastic/kibana
    needs:
      - elasticsearch
    values:
      - kibanaConfig:
          kibana.yml: |
            server.basePath: /kibana
            server.rewriteBasePath: true
            server.publicBaseUrl: https://{{ .Values.cluster.domain }}/kibana
      - healthCheckPath: "/kibana/login"
      - ingress:
          enabled: true
          pathtype: Prefix
          hosts:
            - host: {{ .Values.cluster.domain }}
              paths:
                - path: /kibana
